export declare const ACTION_OPTIONS_METADATA_KEY: string;
export declare const ACTION_DECLARATION_METADATA_KEY: string;
export declare const ACTION_BINDINGS_METADATA_KEY: string;
export declare const ACTION_EXCEPTION_FILTER_METADATA_KEY: string;
export declare const CONTROLLER_OPTIONS_METADATA_KEY: string;
export declare const CONTROLLER_EXCEPTION_FILTER_METADATA_KEY: string;
export declare const AUTH_ROLES_METADATA_KEY: string;
export declare const AUTH_ANONYMOUS_METADATA_KEY: string;
export declare const VALIDATION_VALIDATORS_KEY: string;
