"use strict";
exports.ACTION_OPTIONS_METADATA_KEY = 'Action:options';
exports.ACTION_DECLARATION_METADATA_KEY = 'Action:declaration';
exports.ACTION_BINDINGS_METADATA_KEY = 'Action:bindings';
exports.ACTION_EXCEPTION_FILTER_METADATA_KEY = 'Action:exception-filter';
exports.CONTROLLER_OPTIONS_METADATA_KEY = 'ApiController:options';
exports.CONTROLLER_EXCEPTION_FILTER_METADATA_KEY = 'ApiController:exception-filter';
exports.AUTH_ROLES_METADATA_KEY = 'auth:roles';
exports.AUTH_ANONYMOUS_METADATA_KEY = 'auth:anonymous';
exports.VALIDATION_VALIDATORS_KEY = 'validation:validators';
